config/routes.rb
Rails.application.routes.draw do
 resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save!

    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for(@article) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :content %>
  <%= t.text_field :content %>

  <%= t.submit %>
<% end %>

app/views/articles/index.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">WIKINIMOUS</a>
  <form class="form-inline">
      <a href="/articles/new">New Article</a>
  </form>
</nav>


<div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
<ul>
  <% @articles.each do |article| %>
    <li><%=link_to(article.title, article_path(article), class: "title")%></li>
    <li class="content"><%= article.content%></li>
  <% end %>
</ul>
      </div>
    </div>
</div>

app/views/articles/new.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">WIKINIMOUS</a>
  <form class="form-inline">
      <a href="/articles/new">New Article</a>
  </form>
</nav>

<%= form_for(@article) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :content %>
  <%= t.text_field :content %>

  <%= t.submit %>
<% end %>

<form action="" method="POST" role="form" style="margin-left:270px; margin-top:20px;">


            <div class="form-group">
                <label for="">Title</label>
                <input type="text" class="form-control" id="" placeholder="Moby Dick">
            </div>
            <div class="form-group">
                <label for="">Content</label>
                <input type="text" class="form-control" id="" placeholder="Lorem ipsum sit amet">
            </div>



            <button type="submit" class="btn btn-success">Create Article</button>
        </form>


<a class ="btn btn-primary" href="/articles">Back</a>
      </div>
    </div>

app/views/articles/show.html.erb
<%= link_to "Back", articles_path %>
<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Delete",
            article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

<h1>article</h1>

<p>Name: <%= @article.title %></p>
<p>Description: <%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>